# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ARM32

    steps:
    - name: Update packages
      run: sudo apt-get -y update
    - name: Get JDK
      run: sudo apt-get -y install openjdk-11-jdk
    - name: Get JFX
      run: sudo apt-get -y install openjfx
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jlink
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: mea
        # Destination path
        path: build/image/
